---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-19.10
    image: ubuntu:19.10 # TODO: Use a pre-built image instead
    privileged: True
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env:
      UBUNTU_RELEASE_CODE_NAME: eoan
    command: /usr/sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
