---
- name: Install prerequisites
  include_tasks: prerequisites.yml
  when: tomcat_sample_install_prereqs

- name: Create temporary directory
  tempfile:
    state: directory
  changed_when: False
  register: temp_dir

- name: Copy {{ role_path }}/{{ tomcat_sample_pytest_health_script_basename }} to {{ temp_dir.path }}
  copy:
    src: "{{ tomcat_sample_pytest_health_script_basename }}"
    dest: "{{ temp_dir.path }}/{{ tomcat_sample_pytest_health_script_basename }}"
  changed_when: False

- name: Set facts related to {{ tomcat_sample_pytest_health_script_basename }}
  set_fact:
    tomcat_sample_pytest_health_script_env_base_url: >-
      http://localhost:{{ tomcat_sample_docker_container_host_port }}/{{ tomcat_sample_docker_buildarg_war_name }}
    tomcat_sample_pytest_health_script_command: pytest {{ (temp_dir.path + '/' + tomcat_sample_pytest_health_script_basename) | quote }}

- name: Check the application health # noqa 305
  shell: "{{ tomcat_sample_pytest_health_script_command }}"
  environment:
    PYTEST_BASE_URL: "{{ tomcat_sample_pytest_health_script_env_base_url }}"
    PYTEST_BODY_IN: "{{ tomcat_sample_pytest_health_script_env_body_in }}"
  failed_when: False
  changed_when: False
  register: res_healthy

- name: Deploy the application
  include_tasks: deploy.yml
  when: res_healthy.rc != 0

- name: Delete the temporary directory
  file:
    state: absent
    path: "{{ temp_dir.path }}"
  changed_when: False
